[package]
name = "blah"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
baseline = { path = "../baseline" }
log = "0.4.20"
pretty_env_logger = "0.5.0"
